-- Create notifications table for storing user notifications
CREATE TABLE IF NOT EXISTS `notifications` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `user_id` int(11) NOT NULL,
  `account_id` int(11) NOT NULL,
  `title` varchar(255) NOT NULL,
  `message` text NOT NULL,
  `type` ENUM('info', 'success', 'warning', 'error', 'collection', 'sale', 'supplier', 'customer', 'payment', 'system') NOT NULL DEFAULT 'info',
  `category` ENUM('general', 'business', 'financial', 'reminder', 'alert', 'update') NOT NULL DEFAULT 'general',
  `action_url` varchar(500) DEFAULT NULL,
  `action_data` JSON DEFAULT NULL,
  `expires_at` timestamp NULL DEFAULT NULL,
  `created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `status` ENUM('unread', 'read', 'archived', 'deleted') NOT NULL DEFAULT 'unread',
  PRIMARY KEY (`id`),
  KEY `user_id` (`user_id`),
  KEY `account_id` (`account_id`),
  KEY `type` (`type`),
  KEY `category` (`category`),
  KEY `status` (`status`),
  KEY `created_at` (`created_at`),
  KEY `user_account_idx` (`user_id`, `account_id`),
  KEY `read_status_idx` (`user_id`, `account_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
