-- CreateTable
-- This is the initial migration for Gemura database
-- All tables use UUID primary keys with legacy_id for migration reference

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- Note: This migration will be generated by Prisma
-- Run: npx prisma migrate dev --name init
-- Or: npx prisma migrate deploy (for production)

